ALTER TABLE plans
  ADD COLUMN IF NOT EXISTS max_calls INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_presells INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_videos INT NOT NULL DEFAULT 0;
