ALTER TABLE calls
  ADD COLUMN IF NOT EXISTS playback_rate FLOAT NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS video_zoom    FLOAT NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS video_x       FLOAT NOT NULL DEFAULT 0.0,
  ADD COLUMN IF NOT EXISTS video_y       FLOAT NOT NULL DEFAULT 0.0;
